spring.application.name=coffee_search
server.port=8082

# Google Custom Search API Configuration
google.cse.apiKey=AIzaSyAQVUg4wP2W3EhVpGnOgEoFFfdTBKKLo_Q
google.cse.cx=342b427d8ad1b4491

# Google Translation API Configuration (如果使用付費版 Cloud Translation API)
# 若您使用的是免費的 script 方法或其他方式，這裡僅供參考，Service 層會用到
google.translate.apiKey=AIzaSyB100ugmjdeJ3U4Bj5ylhhOA0GP5izdrak

#gemini api key
google.gemini.apiKey=AIzaSyC8P7RNtDjT_HVm60U_VI3_ZUaRhwhuBq4
google.gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
