spring.application.name=coffee_search
server.port=8081

# Google Custom Search API Configuration
google.cse.apiKey=AIzaSyB100ugmjdeJ3U4Bj5ylhhOA0GP5izdrak
google.cse.cx=a44b7351111e44cba

# Google Translation API Configuration (如果使用付費版 Cloud Translation API)
# 若您使用的是免費的 script 方法或其他方式，這裡僅供參考，Service 層會用到
google.translate.apiKey=AIzaSyB100ugmjdeJ3U4Bj5ylhhOA0GP5izdrak
